"""create marketplace content schema

Revision ID: 20260711_0005
Revises: 20260711_0004
Create Date: 2026-07-11 15:12:36.628272
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = "20260711_0005"
down_revision: str | None = "20260711_0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


TABLES_WITH_RLS = (
    "work_cards",
    "work_card_product_types",
    "work_needed_posts",
    "work_needed_post_product_types",
)

TABLES_WITH_UPDATED_AT = (
    "work_cards",
    "work_needed_posts",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "work_cards",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("work_category_id", sa.UUID(), nullable=True),
        sa.Column("work_name_category_id", sa.UUID(), nullable=True),
        sa.Column("custom_work_category_text", sa.Text(), nullable=True),
        sa.Column("custom_work_name", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("experience_years", sa.Integer(), nullable=True),
        sa.Column(
            "status", sa.Text(), server_default=sa.text("'draft'"), nullable=False
        ),
        sa.Column(
            "photo_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "ranking_score",
            sa.Numeric(precision=10, scale=4),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("search_text", sa.Text(), nullable=True),
        sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('draft', 'published', 'hidden_by_user', 'removed_by_admin', 'deleted')",
            name=op.f("ck_work_cards_status_valid"),
        ),
        sa.CheckConstraint(
            "status not in ('published', 'hidden_by_user') or (photo_count >= 3 and (work_category_id is not null or nullif(btrim(custom_work_category_text), '') is not null) and (work_name_category_id is not null or nullif(btrim(custom_work_name), '') is not null))",
            name=op.f("ck_work_cards_publish_requires_required_fields"),
        ),
        sa.CheckConstraint(
            "experience_years is null or experience_years >= 0",
            name=op.f("ck_work_cards_experience_years_non_negative"),
        ),
        sa.CheckConstraint(
            "nullif(btrim(title), '') is not null",
            name=op.f("ck_work_cards_title_non_empty"),
        ),
        sa.CheckConstraint(
            "photo_count >= 0", name=op.f("ck_work_cards_photo_count_non_negative")
        ),
        sa.CheckConstraint(
            "ranking_score >= 0", name=op.f("ck_work_cards_ranking_score_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["job_worker_profiles.profile_id"],
            name=op.f("fk_work_cards_profile_id_job_worker_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["work_category_id"],
            ["categories.id"],
            name=op.f("fk_work_cards_work_category_id_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["work_name_category_id"],
            ["categories.id"],
            name=op.f("fk_work_cards_work_name_category_id_categories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_cards")),
    )
    op.create_index(
        "idx_work_cards_category_status",
        "work_cards",
        ["work_category_id", "work_name_category_id", "status"],
        unique=False,
    )
    op.create_index(
        "idx_work_cards_profile_status",
        "work_cards",
        ["profile_id", "status"],
        unique=False,
    )
    op.create_index(
        "idx_work_cards_ranking",
        "work_cards",
        [
            "status",
            sa.literal_column("ranking_score desc"),
            sa.literal_column("last_activity_at desc"),
        ],
        unique=False,
    )
    op.create_index(
        "idx_work_cards_search_text_trgm",
        "work_cards",
        ["search_text"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"search_text": "gin_trgm_ops"},
    )
    op.create_index(
        "idx_work_cards_search_vector",
        "work_cards",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "work_needed_posts",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("work_category_id", sa.UUID(), nullable=True),
        sa.Column("work_name_category_id", sa.UUID(), nullable=True),
        sa.Column("custom_work_category_text", sa.Text(), nullable=True),
        sa.Column("custom_work_name", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.Text(), server_default=sa.text("'draft'"), nullable=False
        ),
        sa.Column(
            "photo_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "ranking_score",
            sa.Numeric(precision=10, scale=4),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("search_text", sa.Text(), nullable=True),
        sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "closed_at is null or status in ('closed_by_user', 'removed_by_admin', 'deleted')",
            name=op.f("ck_work_needed_posts_closed_at_requires_closed_status"),
        ),
        sa.CheckConstraint(
            "status in ('draft', 'active', 'paused', 'closed_by_user', 'removed_by_admin', 'deleted')",
            name=op.f("ck_work_needed_posts_status_valid"),
        ),
        sa.CheckConstraint(
            "status not in ('active', 'paused', 'closed_by_user') or (photo_count >= 3 and (work_category_id is not null or nullif(btrim(custom_work_category_text), '') is not null) and (work_name_category_id is not null or nullif(btrim(custom_work_name), '') is not null))",
            name=op.f("ck_work_needed_posts_publish_requires_required_fields"),
        ),
        sa.CheckConstraint(
            "nullif(btrim(title), '') is not null",
            name=op.f("ck_work_needed_posts_title_non_empty"),
        ),
        sa.CheckConstraint(
            "photo_count >= 0",
            name=op.f("ck_work_needed_posts_photo_count_non_negative"),
        ),
        sa.CheckConstraint(
            "ranking_score >= 0",
            name=op.f("ck_work_needed_posts_ranking_score_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["business_profiles.profile_id"],
            name=op.f("fk_work_needed_posts_profile_id_business_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["work_category_id"],
            ["categories.id"],
            name=op.f("fk_work_needed_posts_work_category_id_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["work_name_category_id"],
            ["categories.id"],
            name=op.f("fk_work_needed_posts_work_name_category_id_categories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_needed_posts")),
    )
    op.create_index(
        "idx_work_needed_posts_category_status",
        "work_needed_posts",
        ["work_category_id", "work_name_category_id", "status"],
        unique=False,
    )
    op.create_index(
        "idx_work_needed_posts_profile_status",
        "work_needed_posts",
        ["profile_id", "status"],
        unique=False,
    )
    op.create_index(
        "idx_work_needed_posts_ranking",
        "work_needed_posts",
        [
            "status",
            sa.literal_column("ranking_score desc"),
            sa.literal_column("last_activity_at desc"),
        ],
        unique=False,
    )
    op.create_index(
        "idx_work_needed_posts_search_text_trgm",
        "work_needed_posts",
        ["search_text"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"search_text": "gin_trgm_ops"},
    )
    op.create_index(
        "idx_work_needed_posts_search_vector",
        "work_needed_posts",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "work_card_product_types",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("work_card_id", sa.UUID(), nullable=False),
        sa.Column("product_type_category_id", sa.UUID(), nullable=True),
        sa.Column("custom_product_type_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "product_type_category_id is not null or nullif(btrim(custom_product_type_text), '') is not null",
            name=op.f("ck_work_card_product_types_product_type_or_custom_required"),
        ),
        sa.ForeignKeyConstraint(
            ["product_type_category_id"],
            ["categories.id"],
            name=op.f("fk_work_card_product_types_product_type_category_id_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["work_card_id"],
            ["work_cards.id"],
            name=op.f("fk_work_card_product_types_work_card_id_work_cards"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_card_product_types")),
    )
    op.create_index(
        "idx_work_card_product_types_category",
        "work_card_product_types",
        ["product_type_category_id", "work_card_id"],
        unique=False,
    )
    op.create_index(
        "idx_work_card_product_types_work_card",
        "work_card_product_types",
        ["work_card_id"],
        unique=False,
    )
    op.create_index(
        "uq_work_card_product_types_custom",
        "work_card_product_types",
        ["work_card_id", sa.literal_column("lower(btrim(custom_product_type_text))")],
        unique=True,
        postgresql_where=sa.text("custom_product_type_text is not null"),
    )
    op.create_index(
        "uq_work_card_product_types_mapped",
        "work_card_product_types",
        ["work_card_id", "product_type_category_id"],
        unique=True,
        postgresql_where=sa.text("product_type_category_id is not null"),
    )
    op.create_table(
        "work_needed_post_product_types",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("work_needed_post_id", sa.UUID(), nullable=False),
        sa.Column("product_type_category_id", sa.UUID(), nullable=True),
        sa.Column("custom_product_type_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "product_type_category_id is not null or nullif(btrim(custom_product_type_text), '') is not null",
            name=op.f(
                "ck_work_needed_post_product_types_product_type_or_custom_required"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["product_type_category_id"],
            ["categories.id"],
            name=op.f(
                "fk_work_needed_post_product_types_product_type_category_id_categories"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["work_needed_post_id"],
            ["work_needed_posts.id"],
            name=op.f(
                "fk_work_needed_post_product_types_work_needed_post_id_work_needed_posts"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_needed_post_product_types")),
    )
    op.create_index(
        "idx_work_needed_post_product_types_category",
        "work_needed_post_product_types",
        ["product_type_category_id", "work_needed_post_id"],
        unique=False,
    )
    op.create_index(
        "idx_work_needed_post_product_types_post",
        "work_needed_post_product_types",
        ["work_needed_post_id"],
        unique=False,
    )
    op.create_index(
        "uq_work_needed_post_product_types_custom",
        "work_needed_post_product_types",
        [
            "work_needed_post_id",
            sa.literal_column("lower(btrim(custom_product_type_text))"),
        ],
        unique=True,
        postgresql_where=sa.text("custom_product_type_text is not null"),
    )
    op.create_index(
        "uq_work_needed_post_product_types_mapped",
        "work_needed_post_product_types",
        ["work_needed_post_id", "product_type_category_id"],
        unique=True,
        postgresql_where=sa.text("product_type_category_id is not null"),
    )

    for table_name in TABLES_WITH_UPDATED_AT:
        op.execute(
            f"""
            create trigger trg_{table_name}_set_updated_at
            before update on public.{table_name}
            for each row
            execute function public.set_updated_at();
            """
        )

    for table_name in TABLES_WITH_RLS:
        op.execute(f"alter table public.{table_name} enable row level security")

    op.execute(
        f"""
        do $$
        begin
          if exists (select 1 from pg_roles where rolname = 'anon') then
            revoke all on {", ".join("public." + table for table in TABLES_WITH_RLS)} from anon;
          end if;
          if exists (select 1 from pg_roles where rolname = 'authenticated') then
            revoke all on {", ".join("public." + table for table in TABLES_WITH_RLS)} from authenticated;
          end if;
        end $$;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in reversed(TABLES_WITH_UPDATED_AT):
        op.execute(
            f"drop trigger if exists trg_{table_name}_set_updated_at on public.{table_name}"
        )

    op.drop_index(
        "uq_work_needed_post_product_types_mapped",
        table_name="work_needed_post_product_types",
        postgresql_where=sa.text("product_type_category_id is not null"),
    )
    op.drop_index(
        "uq_work_needed_post_product_types_custom",
        table_name="work_needed_post_product_types",
        postgresql_where=sa.text("custom_product_type_text is not null"),
    )
    op.drop_index(
        "idx_work_needed_post_product_types_post",
        table_name="work_needed_post_product_types",
    )
    op.drop_index(
        "idx_work_needed_post_product_types_category",
        table_name="work_needed_post_product_types",
    )
    op.drop_table("work_needed_post_product_types")
    op.drop_index(
        "uq_work_card_product_types_mapped",
        table_name="work_card_product_types",
        postgresql_where=sa.text("product_type_category_id is not null"),
    )
    op.drop_index(
        "uq_work_card_product_types_custom",
        table_name="work_card_product_types",
        postgresql_where=sa.text("custom_product_type_text is not null"),
    )
    op.drop_index(
        "idx_work_card_product_types_work_card", table_name="work_card_product_types"
    )
    op.drop_index(
        "idx_work_card_product_types_category", table_name="work_card_product_types"
    )
    op.drop_table("work_card_product_types")
    op.drop_index(
        "idx_work_needed_posts_search_vector",
        table_name="work_needed_posts",
        postgresql_using="gin",
    )
    op.drop_index(
        "idx_work_needed_posts_search_text_trgm",
        table_name="work_needed_posts",
        postgresql_using="gin",
        postgresql_ops={"search_text": "gin_trgm_ops"},
    )
    op.drop_index("idx_work_needed_posts_ranking", table_name="work_needed_posts")
    op.drop_index(
        "idx_work_needed_posts_profile_status", table_name="work_needed_posts"
    )
    op.drop_index(
        "idx_work_needed_posts_category_status", table_name="work_needed_posts"
    )
    op.drop_table("work_needed_posts")
    op.drop_index(
        "idx_work_cards_search_vector", table_name="work_cards", postgresql_using="gin"
    )
    op.drop_index(
        "idx_work_cards_search_text_trgm",
        table_name="work_cards",
        postgresql_using="gin",
        postgresql_ops={"search_text": "gin_trgm_ops"},
    )
    op.drop_index("idx_work_cards_ranking", table_name="work_cards")
    op.drop_index("idx_work_cards_profile_status", table_name="work_cards")
    op.drop_index("idx_work_cards_category_status", table_name="work_cards")
    op.drop_table("work_cards")
    # ### end Alembic commands ###
