"""create profile schema

Revision ID: 20260711_0004
Revises: 20260711_0003
Create Date: 2026-07-11 14:53:33.507643
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = "20260711_0004"
down_revision: str | None = "20260711_0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


TABLES_WITH_RLS = (
    "profiles",
    "business_profiles",
    "business_profile_product_types",
    "profile_business_subtypes",
    "job_worker_profiles",
    "skilled_worker_profiles",
    "profile_gst_details",
    "profile_change_history",
)

TABLES_WITH_UPDATED_AT = (
    "profiles",
    "business_profiles",
    "job_worker_profiles",
    "skilled_worker_profiles",
    "profile_gst_details",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("public_name", sa.Text(), nullable=True),
        sa.Column("owner_name", sa.Text(), nullable=True),
        sa.Column("alternate_contact_number", sa.Text(), nullable=True),
        sa.Column("full_address", sa.Text(), nullable=True),
        sa.Column("address_line1", sa.Text(), nullable=True),
        sa.Column("address_line2", sa.Text(), nullable=True),
        sa.Column("locality", sa.Text(), nullable=True),
        sa.Column("normalized_locality", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("state", sa.Text(), nullable=True),
        sa.Column("pincode", sa.Text(), nullable=True),
        sa.Column(
            "visibility_status",
            sa.Text(),
            server_default=sa.text("'draft'"),
            nullable=False,
        ),
        sa.Column(
            "verification_status",
            sa.Text(),
            server_default=sa.text("'unverified'"),
            nullable=False,
        ),
        sa.Column(
            "completion_score",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "completion_flags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "photo_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "is_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "ranking_score",
            sa.Numeric(precision=10, scale=4),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("search_text", sa.Text(), nullable=True),
        sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column(
            "is_admin_seeded",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("created_by_admin_user_id", sa.UUID(), nullable=True),
        sa.Column("claim_status", sa.Text(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "claim_status is null or claim_status in ('unclaimed', 'claimed', 'not_claimable')",
            name=op.f("ck_profiles_claim_status_valid"),
        ),
        sa.CheckConstraint(
            "is_verified = false or verification_status = 'verified'",
            name=op.f("ck_profiles_verified_flag_requires_verified_status"),
        ),
        sa.CheckConstraint(
            "role in ('business', 'job_worker', 'skilled_worker')",
            name=op.f("ck_profiles_role_valid"),
        ),
        sa.CheckConstraint(
            "verification_status in ('unverified', 'pending', 'verified', 'changes_requested', 'rejected')",
            name=op.f("ck_profiles_verification_status_valid"),
        ),
        sa.CheckConstraint(
            "visibility_status in ('draft', 'public', 'hidden_by_user', 'suspended_by_admin', 'deleted')",
            name=op.f("ck_profiles_visibility_status_valid"),
        ),
        sa.CheckConstraint(
            "completion_score between 0 and 100",
            name=op.f("ck_profiles_completion_score_valid"),
        ),
        sa.CheckConstraint(
            "owner_user_id is not null or is_admin_seeded = true",
            name=op.f("ck_profiles_owner_or_admin_seeded_required"),
        ),
        sa.CheckConstraint(
            "photo_count >= 0", name=op.f("ck_profiles_photo_count_non_negative")
        ),
        sa.CheckConstraint(
            "ranking_score >= 0", name=op.f("ck_profiles_ranking_score_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_admin_user_id"],
            ["admin_users.id"],
            name=op.f("fk_profiles_created_by_admin_user_id_admin_users"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_profiles_owner_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profiles")),
    )
    op.create_index(
        "idx_profiles_created_by_admin",
        "profiles",
        ["created_by_admin_user_id"],
        unique=False,
    )
    op.create_index(
        "idx_profiles_location",
        "profiles",
        ["state", "city", "normalized_locality", "pincode"],
        unique=False,
    )
    op.create_index("idx_profiles_owner", "profiles", ["owner_user_id"], unique=False)
    op.create_index(
        "idx_profiles_ranking",
        "profiles",
        [
            "role",
            "visibility_status",
            sa.literal_column("ranking_score desc"),
            sa.literal_column("last_activity_at desc"),
        ],
        unique=False,
    )
    op.create_index(
        "idx_profiles_role_visibility",
        "profiles",
        ["role", "visibility_status", "verification_status"],
        unique=False,
    )
    op.create_index(
        "idx_profiles_search_text_trgm",
        "profiles",
        ["search_text"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"search_text": "gin_trgm_ops"},
    )
    op.create_index(
        "idx_profiles_search_vector",
        "profiles",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "uq_profiles_owner_active",
        "profiles",
        ["owner_user_id"],
        unique=True,
        postgresql_where=sa.text("owner_user_id is not null and deleted_at is null"),
    )
    op.create_table(
        "business_profiles",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("business_name", sa.Text(), nullable=False),
        sa.Column("business_category_id", sa.UUID(), nullable=True),
        sa.Column("manufacture_sell_details", sa.Text(), nullable=False),
        sa.Column("product_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_category_id"],
            ["categories.id"],
            name=op.f("fk_business_profiles_business_category_id_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_business_profiles_profile_id_profiles"),
        ),
        sa.PrimaryKeyConstraint("profile_id", name=op.f("pk_business_profiles")),
    )
    op.create_index(
        "idx_business_profiles_business_category",
        "business_profiles",
        ["business_category_id"],
        unique=False,
    )
    op.create_table(
        "job_worker_profiles",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("workshop_name", sa.Text(), nullable=True),
        sa.Column(
            "has_workshop", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("work_summary", sa.Text(), nullable=True),
        sa.Column("profile_experience_years", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "profile_experience_years is null or profile_experience_years >= 0",
            name=op.f("ck_job_worker_profiles_profile_experience_years_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_job_worker_profiles_profile_id_profiles"),
        ),
        sa.PrimaryKeyConstraint("profile_id", name=op.f("pk_job_worker_profiles")),
    )
    op.create_table(
        "profile_change_history",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("changed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("changed_by_admin_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "changed_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "before_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("after_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "requires_reverification",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "changed_by_user_id is not null or changed_by_admin_user_id is not null",
            name=op.f("ck_profile_change_history_changed_by_actor_required"),
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_admin_user_id"],
            ["admin_users.id"],
            name=op.f("fk_profile_change_history_changed_by_admin_user_id_admin_users"),
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_user_id"],
            ["users.id"],
            name=op.f("fk_profile_change_history_changed_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_profile_change_history_profile_id_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_change_history")),
    )
    op.create_index(
        "idx_profile_change_history_admin",
        "profile_change_history",
        ["changed_by_admin_user_id"],
        unique=False,
    )
    op.create_index(
        "idx_profile_change_history_profile",
        "profile_change_history",
        ["profile_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_profile_change_history_reverification",
        "profile_change_history",
        ["requires_reverification", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_profile_change_history_user",
        "profile_change_history",
        ["changed_by_user_id"],
        unique=False,
    )
    op.create_table(
        "profile_gst_details",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("gstin", sa.Text(), nullable=False),
        sa.Column("gst_legal_name", sa.Text(), nullable=True),
        sa.Column("gst_trade_name", sa.Text(), nullable=True),
        sa.Column("gst_status", sa.Text(), nullable=True),
        sa.Column(
            "review_status",
            sa.Text(),
            server_default=sa.text("'unreviewed'"),
            nullable=False,
        ),
        sa.Column("proof_media_asset_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_by_admin_user_id", sa.UUID(), nullable=True),
        sa.Column("gst_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "review_status in ('unreviewed', 'pending', 'approved', 'rejected')",
            name=op.f("ck_profile_gst_details_review_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_profile_gst_details_profile_id_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_admin_user_id"],
            ["admin_users.id"],
            name=op.f("fk_profile_gst_details_reviewed_by_admin_user_id_admin_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_gst_details")),
        sa.UniqueConstraint(
            "profile_id", name=op.f("uq_profile_gst_details_profile_id")
        ),
    )
    op.create_index(
        "idx_profile_gst_details_profile",
        "profile_gst_details",
        ["profile_id"],
        unique=False,
    )
    op.create_index(
        "idx_profile_gst_details_proof_media",
        "profile_gst_details",
        ["proof_media_asset_id"],
        unique=False,
    )
    op.create_index(
        "idx_profile_gst_details_review_status",
        "profile_gst_details",
        ["review_status"],
        unique=False,
    )
    op.create_index(
        "idx_profile_gst_details_reviewed_by",
        "profile_gst_details",
        ["reviewed_by_admin_user_id"],
        unique=False,
    )
    op.create_table(
        "skilled_worker_profiles",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("primary_skill_category_id", sa.UUID(), nullable=True),
        sa.Column("skill_mastery", sa.Text(), nullable=False),
        sa.Column(
            "experience_years",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "experience_years >= 0",
            name=op.f("ck_skilled_worker_profiles_experience_years_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["primary_skill_category_id"],
            ["categories.id"],
            name=op.f(
                "fk_skilled_worker_profiles_primary_skill_category_id_categories"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_skilled_worker_profiles_profile_id_profiles"),
        ),
        sa.PrimaryKeyConstraint("profile_id", name=op.f("pk_skilled_worker_profiles")),
    )
    op.create_index(
        "idx_skilled_worker_profiles_skill",
        "skilled_worker_profiles",
        ["primary_skill_category_id"],
        unique=False,
    )
    op.create_table(
        "business_profile_product_types",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("product_type_category_id", sa.UUID(), nullable=True),
        sa.Column("custom_product_type_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "product_type_category_id is not null or custom_product_type_text is not null",
            name=op.f(
                "ck_business_profile_product_types_product_type_or_custom_required"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["product_type_category_id"],
            ["categories.id"],
            name=op.f(
                "fk_business_profile_product_types_product_type_category_id_categories"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["business_profiles.profile_id"],
            name=op.f("fk_business_profile_product_types_profile_id_business_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_profile_product_types")),
    )
    op.create_index(
        "idx_business_profile_product_types_category",
        "business_profile_product_types",
        ["product_type_category_id", "profile_id"],
        unique=False,
    )
    op.create_index(
        "idx_business_profile_product_types_profile",
        "business_profile_product_types",
        ["profile_id"],
        unique=False,
    )
    op.create_index(
        "uq_business_profile_product_types_mapped",
        "business_profile_product_types",
        ["profile_id", "product_type_category_id"],
        unique=True,
        postgresql_where=sa.text("product_type_category_id is not null"),
    )
    op.create_table(
        "profile_business_subtypes",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("business_subtype_id", sa.UUID(), nullable=False),
        sa.Column("free_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_subtype_id"],
            ["business_subtypes.id"],
            name=op.f(
                "fk_profile_business_subtypes_business_subtype_id_business_subtypes"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["business_profiles.profile_id"],
            name=op.f("fk_profile_business_subtypes_profile_id_business_profiles"),
        ),
        sa.PrimaryKeyConstraint(
            "profile_id",
            "business_subtype_id",
            name=op.f("pk_profile_business_subtypes"),
        ),
    )
    op.create_index(
        "idx_profile_business_subtypes_subtype",
        "profile_business_subtypes",
        ["business_subtype_id", "profile_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_category_suggestions_profile_id_profiles"),
        "category_suggestions",
        "profiles",
        ["profile_id"],
        ["id"],
    )

    for table_name in TABLES_WITH_UPDATED_AT:
        op.execute(
            f"""
            create trigger trg_{table_name}_set_updated_at
            before update on public.{table_name}
            for each row
            execute function public.set_updated_at();
            """
        )

    for table_name in TABLES_WITH_RLS:
        op.execute(f"alter table public.{table_name} enable row level security")

    op.execute(
        f"""
        do $$
        begin
          if exists (select 1 from pg_roles where rolname = 'anon') then
            revoke all on {", ".join("public." + table for table in TABLES_WITH_RLS)} from anon;
          end if;
          if exists (select 1 from pg_roles where rolname = 'authenticated') then
            revoke all on {", ".join("public." + table for table in TABLES_WITH_RLS)} from authenticated;
          end if;
        end $$;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in reversed(TABLES_WITH_UPDATED_AT):
        op.execute(
            f"drop trigger if exists trg_{table_name}_set_updated_at on public.{table_name}"
        )

    op.drop_constraint(
        op.f("fk_category_suggestions_profile_id_profiles"),
        "category_suggestions",
        type_="foreignkey",
    )
    op.drop_index(
        "idx_profile_business_subtypes_subtype", table_name="profile_business_subtypes"
    )
    op.drop_table("profile_business_subtypes")
    op.drop_index(
        "uq_business_profile_product_types_mapped",
        table_name="business_profile_product_types",
        postgresql_where=sa.text("product_type_category_id is not null"),
    )
    op.drop_index(
        "idx_business_profile_product_types_profile",
        table_name="business_profile_product_types",
    )
    op.drop_index(
        "idx_business_profile_product_types_category",
        table_name="business_profile_product_types",
    )
    op.drop_table("business_profile_product_types")
    op.drop_index(
        "idx_skilled_worker_profiles_skill", table_name="skilled_worker_profiles"
    )
    op.drop_table("skilled_worker_profiles")
    op.drop_index(
        "idx_profile_gst_details_reviewed_by", table_name="profile_gst_details"
    )
    op.drop_index(
        "idx_profile_gst_details_review_status", table_name="profile_gst_details"
    )
    op.drop_index(
        "idx_profile_gst_details_proof_media", table_name="profile_gst_details"
    )
    op.drop_index("idx_profile_gst_details_profile", table_name="profile_gst_details")
    op.drop_table("profile_gst_details")
    op.drop_index(
        "idx_profile_change_history_user", table_name="profile_change_history"
    )
    op.drop_index(
        "idx_profile_change_history_reverification", table_name="profile_change_history"
    )
    op.drop_index(
        "idx_profile_change_history_profile", table_name="profile_change_history"
    )
    op.drop_index(
        "idx_profile_change_history_admin", table_name="profile_change_history"
    )
    op.drop_table("profile_change_history")
    op.drop_table("job_worker_profiles")
    op.drop_index(
        "idx_business_profiles_business_category", table_name="business_profiles"
    )
    op.drop_table("business_profiles")
    op.drop_index(
        "uq_profiles_owner_active",
        table_name="profiles",
        postgresql_where=sa.text("owner_user_id is not null and deleted_at is null"),
    )
    op.drop_index(
        "idx_profiles_search_vector", table_name="profiles", postgresql_using="gin"
    )
    op.drop_index(
        "idx_profiles_search_text_trgm",
        table_name="profiles",
        postgresql_using="gin",
        postgresql_ops={"search_text": "gin_trgm_ops"},
    )
    op.drop_index("idx_profiles_role_visibility", table_name="profiles")
    op.drop_index("idx_profiles_ranking", table_name="profiles")
    op.drop_index("idx_profiles_owner", table_name="profiles")
    op.drop_index("idx_profiles_location", table_name="profiles")
    op.drop_index("idx_profiles_created_by_admin", table_name="profiles")
    op.drop_table("profiles")
    # ### end Alembic commands ###
