"""create cross cutting schema

Revision ID: 20260711_0006
Revises: 20260711_0005
Create Date: 2026-07-12 10:01:32.882004
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = "20260711_0006"
down_revision: str | None = "20260711_0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


TABLES_WITH_RLS = (
    "subscription_plans",
    "media_assets",
    "notifications",
    "saved_items",
    "search_logs",
    "share_events",
    "user_contact_quotas",
    "user_subscriptions",
    "admin_access_grants",
    "payment_transactions",
    "reports",
    "contact_action_events",
    "contact_reveals",
    "profile_view_events",
    "verification_cases",
    "verification_checks",
    "verification_provider_checks",
)

TABLES_WITH_UPDATED_AT = (
    "subscription_plans",
    "media_assets",
    "user_contact_quotas",
    "user_subscriptions",
    "admin_access_grants",
    "payment_transactions",
    "reports",
    "contact_reveals",
    "verification_cases",
    "verification_checks",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription_plans",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("billing_period", sa.Text(), nullable=False),
        sa.Column("price_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "currency", sa.Text(), server_default=sa.text("'INR'"), nullable=False
        ),
        sa.Column(
            "features_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "billing_period in ('monthly', 'yearly')",
            name=op.f("ck_subscription_plans_billing_period_valid"),
        ),
        sa.CheckConstraint(
            "nullif(btrim(code), '') is not null",
            name=op.f("ck_subscription_plans_code_non_empty"),
        ),
        sa.CheckConstraint(
            "nullif(btrim(currency), '') is not null",
            name=op.f("ck_subscription_plans_currency_non_empty"),
        ),
        sa.CheckConstraint(
            "nullif(btrim(name), '') is not null",
            name=op.f("ck_subscription_plans_name_non_empty"),
        ),
        sa.CheckConstraint(
            "price_amount is null or price_amount >= 0",
            name=op.f("ck_subscription_plans_price_amount_non_negative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_plans")),
        sa.UniqueConstraint("code", name=op.f("uq_subscription_plans_code")),
    )
    op.create_index(
        "idx_subscription_plans_active",
        "subscription_plans",
        ["is_active", "billing_period"],
        unique=False,
    )
    op.create_table(
        "media_assets",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("media_kind", sa.Text(), nullable=False),
        sa.Column("document_type", sa.Text(), nullable=True),
        sa.Column("visibility", sa.Text(), nullable=False),
        sa.Column(
            "upload_status",
            sa.Text(),
            server_default=sa.text("'pending_upload'"),
            nullable=False,
        ),
        sa.Column("original_path", sa.Text(), nullable=False),
        sa.Column("compressed_path", sa.Text(), nullable=True),
        sa.Column("thumbnail_path", sa.Text(), nullable=True),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("mime_type", sa.Text(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("uploaded_by_user_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "document_type is null or document_type in ('identity_proof', 'masked_aadhaar', 'gst_proof', 'shop_photo', 'workplace_photo', 'other')",
            name=op.f("ck_media_assets_document_type_valid"),
        ),
        sa.CheckConstraint(
            "document_type not in ('identity_proof', 'masked_aadhaar', 'gst_proof') or visibility = 'private_admin_only'",
            name=op.f("ck_media_assets_proof_documents_are_private"),
        ),
        sa.CheckConstraint(
            "entity_type in ('profile', 'work_card', 'work_needed_post', 'verification_case')",
            name=op.f("ck_media_assets_entity_type_valid"),
        ),
        sa.CheckConstraint(
            "media_kind <> 'document' or visibility = 'private_admin_only'",
            name=op.f("ck_media_assets_document_media_is_private"),
        ),
        sa.CheckConstraint(
            "media_kind in ('image', 'document')",
            name=op.f("ck_media_assets_media_kind_valid"),
        ),
        sa.CheckConstraint(
            "nullif(btrim(original_path), '') is not null",
            name=op.f("ck_media_assets_original_path_non_empty"),
        ),
        sa.CheckConstraint(
            "upload_status in ('pending_upload', 'uploaded', 'processing', 'ready', 'failed', 'deleted')",
            name=op.f("ck_media_assets_upload_status_valid"),
        ),
        sa.CheckConstraint(
            "visibility in ('public', 'private_admin_only')",
            name=op.f("ck_media_assets_visibility_valid"),
        ),
        sa.CheckConstraint(
            "file_size_bytes is null or file_size_bytes >= 0",
            name=op.f("ck_media_assets_file_size_bytes_non_negative"),
        ),
        sa.CheckConstraint(
            "height is null or height > 0", name=op.f("ck_media_assets_height_positive")
        ),
        sa.CheckConstraint(
            "sort_order >= 0", name=op.f("ck_media_assets_sort_order_non_negative")
        ),
        sa.CheckConstraint(
            "width is null or width > 0", name=op.f("ck_media_assets_width_positive")
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
            name=op.f("fk_media_assets_uploaded_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
    )
    op.create_index(
        "idx_media_assets_entity",
        "media_assets",
        ["entity_type", "entity_id", "visibility", "upload_status", "sort_order"],
        unique=False,
    )
    op.create_index(
        "idx_media_assets_private_documents",
        "media_assets",
        ["entity_type", "entity_id", "document_type"],
        unique=False,
        postgresql_where=sa.text("visibility = 'private_admin_only'"),
    )
    op.create_index(
        "idx_media_assets_status",
        "media_assets",
        ["upload_status", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_media_assets_uploaded_by",
        "media_assets",
        ["uploaded_by_user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("notification_type", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "data_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "priority", sa.Text(), server_default=sa.text("'normal'"), nullable=False
        ),
        sa.Column("push_status", sa.Text(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "nullif(btrim(message), '') is not null",
            name=op.f("ck_notifications_message_non_empty"),
        ),
        sa.CheckConstraint(
            "nullif(btrim(notification_type), '') is not null",
            name=op.f("ck_notifications_notification_type_non_empty"),
        ),
        sa.CheckConstraint(
            "nullif(btrim(title), '') is not null",
            name=op.f("ck_notifications_title_non_empty"),
        ),
        sa.CheckConstraint(
            "priority in ('low', 'normal', 'high')",
            name=op.f("ck_notifications_priority_valid"),
        ),
        sa.CheckConstraint(
            "push_status is null or push_status in ('not_sent', 'sent', 'failed')",
            name=op.f("ck_notifications_push_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notifications_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "idx_notifications_unread",
        "notifications",
        ["user_id", sa.literal_column("created_at desc")],
        unique=False,
        postgresql_where=sa.text("read_at is null"),
    )
    op.create_index(
        "idx_notifications_user_created",
        "notifications",
        ["user_id", sa.literal_column("created_at desc")],
        unique=False,
    )
    op.create_table(
        "saved_items",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("target_type", sa.Text(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "target_type in ('profile', 'work_card', 'work_needed_post')",
            name=op.f("ck_saved_items_target_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_saved_items_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_items")),
        sa.UniqueConstraint(
            "user_id", "target_type", "target_id", name=op.f("uq_saved_items_user_id")
        ),
    )
    op.create_index(
        "idx_saved_items_target",
        "saved_items",
        ["target_type", "target_id"],
        unique=False,
    )
    op.create_index(
        "idx_saved_items_user",
        "saved_items",
        ["user_id", sa.literal_column("created_at desc")],
        unique=False,
    )
    op.create_table(
        "search_logs",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("query", sa.Text(), nullable=True),
        sa.Column("normalized_query", sa.Text(), nullable=True),
        sa.Column("target_persona", sa.Text(), nullable=False),
        sa.Column(
            "filters_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "result_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "target_persona in ('business', 'job_worker', 'skilled_worker')",
            name=op.f("ck_search_logs_target_persona_valid"),
        ),
        sa.CheckConstraint(
            "result_count >= 0", name=op.f("ck_search_logs_result_count_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_search_logs_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_logs")),
    )
    op.create_index(
        "idx_search_logs_created_at",
        "search_logs",
        [sa.literal_column("created_at desc")],
        unique=False,
    )
    op.create_index(
        "idx_search_logs_target_created",
        "search_logs",
        ["target_persona", sa.literal_column("created_at desc")],
        unique=False,
    )
    op.create_index(
        "idx_search_logs_user_created",
        "search_logs",
        ["user_id", sa.literal_column("created_at desc")],
        unique=False,
    )
    op.create_table(
        "share_events",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("target_type", sa.Text(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=True),
        sa.Column("share_channel", sa.Text(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("device_id", sa.Text(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "share_channel is null or share_channel in ('whatsapp', 'sms', 'x', 'email', 'linkedin', 'system_share')",
            name=op.f("ck_share_events_share_channel_valid"),
        ),
        sa.CheckConstraint(
            "target_type = 'app_invite' or target_id is not null",
            name=op.f("ck_share_events_non_invite_share_requires_target"),
        ),
        sa.CheckConstraint(
            "target_type in ('profile', 'work_card', 'work_needed_post', 'app_invite')",
            name=op.f("ck_share_events_target_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_share_events_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_share_events")),
    )
    op.create_index(
        "idx_share_events_target",
        "share_events",
        ["target_type", "target_id"],
        unique=False,
    )
    op.create_index(
        "idx_share_events_user_created",
        "share_events",
        ["user_id", sa.literal_column("created_at desc")],
        unique=False,
    )
    op.create_table(
        "user_contact_quotas",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "free_reveals_total",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "free_reveals_used",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "verified_bonus_total",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "verified_bonus_used",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "subscription_reveals_unlimited",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "free_reveals_total >= 0 and free_reveals_used >= 0 and verified_bonus_total >= 0 and verified_bonus_used >= 0",
            name=op.f("ck_user_contact_quotas_quota_counts_non_negative"),
        ),
        sa.CheckConstraint(
            "free_reveals_used <= free_reveals_total",
            name=op.f("ck_user_contact_quotas_free_reveals_used_within_total"),
        ),
        sa.CheckConstraint(
            "verified_bonus_used <= verified_bonus_total",
            name=op.f("ck_user_contact_quotas_verified_bonus_used_within_total"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_contact_quotas_user_id_users")
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_contact_quotas")),
    )
    op.create_table(
        "user_subscriptions",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider", sa.Text(), nullable=True),
        sa.Column("provider_subscription_id", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('active', 'cancelled', 'expired', 'payment_pending')",
            name=op.f("ck_user_subscriptions_status_valid"),
        ),
        sa.CheckConstraint(
            "current_period_start is null or current_period_end is null or current_period_end >= current_period_start",
            name=op.f("ck_user_subscriptions_current_period_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["subscription_plans.id"],
            name=op.f("fk_user_subscriptions_plan_id_subscription_plans"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_subscriptions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_subscriptions")),
    )
    op.create_index(
        "idx_user_subscriptions_plan_status",
        "user_subscriptions",
        ["plan_id", "status"],
        unique=False,
    )
    op.create_index(
        "idx_user_subscriptions_provider",
        "user_subscriptions",
        ["provider", "provider_subscription_id"],
        unique=False,
    )
    op.create_index(
        "idx_user_subscriptions_user_status",
        "user_subscriptions",
        ["user_id", "status"],
        unique=False,
    )
    op.create_table(
        "admin_access_grants",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("grant_type", sa.Text(), nullable=False),
        sa.Column("quota_amount", sa.Integer(), nullable=True),
        sa.Column(
            "status", sa.Text(), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("granted_by_admin_user_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "grant_type <> 'extra_quota' or quota_amount is not null",
            name=op.f("ck_admin_access_grants_extra_quota_requires_amount"),
        ),
        sa.CheckConstraint(
            "grant_type in ('free_unlimited', 'extra_quota')",
            name=op.f("ck_admin_access_grants_grant_type_valid"),
        ),
        sa.CheckConstraint(
            "status in ('active', 'revoked', 'expired')",
            name=op.f("ck_admin_access_grants_status_valid"),
        ),
        sa.CheckConstraint(
            "quota_amount is null or quota_amount > 0",
            name=op.f("ck_admin_access_grants_quota_amount_positive"),
        ),
        sa.CheckConstraint(
            "starts_at is null or ends_at is null or ends_at >= starts_at",
            name=op.f("ck_admin_access_grants_grant_period_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["granted_by_admin_user_id"],
            ["admin_users.id"],
            name=op.f("fk_admin_access_grants_granted_by_admin_user_id_admin_users"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_admin_access_grants_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_access_grants")),
    )
    op.create_index(
        "idx_admin_access_grants_admin",
        "admin_access_grants",
        ["granted_by_admin_user_id"],
        unique=False,
    )
    op.create_index(
        "idx_admin_access_grants_user_status",
        "admin_access_grants",
        ["user_id", "status"],
        unique=False,
    )
    op.create_table(
        "payment_transactions",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=True),
        sa.Column("provider", sa.Text(), nullable=True),
        sa.Column("provider_payment_id", sa.Text(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "currency", sa.Text(), server_default=sa.text("'INR'"), nullable=False
        ),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "raw_payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "nullif(btrim(currency), '') is not null",
            name=op.f("ck_payment_transactions_currency_non_empty"),
        ),
        sa.CheckConstraint(
            "status in ('created', 'paid', 'failed', 'refunded')",
            name=op.f("ck_payment_transactions_status_valid"),
        ),
        sa.CheckConstraint(
            "amount is null or amount >= 0",
            name=op.f("ck_payment_transactions_amount_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["user_subscriptions.id"],
            name=op.f("fk_payment_transactions_subscription_id_user_subscriptions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_payment_transactions_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_transactions")),
    )
    op.create_index(
        "idx_payment_transactions_provider_payment",
        "payment_transactions",
        ["provider", "provider_payment_id"],
        unique=False,
    )
    op.create_index(
        "idx_payment_transactions_subscription",
        "payment_transactions",
        ["subscription_id"],
        unique=False,
    )
    op.create_index(
        "idx_payment_transactions_user_created",
        "payment_transactions",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "reports",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("reporter_user_id", sa.UUID(), nullable=False),
        sa.Column("reported_entity_type", sa.Text(), nullable=False),
        sa.Column("reported_entity_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.Text(), server_default=sa.text("'submitted'"), nullable=False
        ),
        sa.Column("reviewed_by_admin_user_id", sa.UUID(), nullable=True),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reason in ('wrong_contact', 'wrong_category', 'inappropriate_photo', 'wrong_details', 'fake_profile', 'spam', 'other')",
            name=op.f("ck_reports_reason_valid"),
        ),
        sa.CheckConstraint(
            "reported_entity_type in ('profile', 'work_card', 'work_needed_post', 'media_asset')",
            name=op.f("ck_reports_reported_entity_type_valid"),
        ),
        sa.CheckConstraint(
            "status in ('submitted', 'in_review', 'resolved_no_action', 'action_taken', 'dismissed')",
            name=op.f("ck_reports_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["reporter_user_id"],
            ["users.id"],
            name=op.f("fk_reports_reporter_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_admin_user_id"],
            ["admin_users.id"],
            name=op.f("fk_reports_reviewed_by_admin_user_id_admin_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index(
        "idx_reports_reporter",
        "reports",
        ["reporter_user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_reports_reviewed_by",
        "reports",
        ["reviewed_by_admin_user_id"],
        unique=False,
    )
    op.create_index(
        "idx_reports_status",
        "reports",
        ["status", sa.literal_column("created_at desc")],
        unique=False,
    )
    op.create_index(
        "idx_reports_target",
        "reports",
        ["reported_entity_type", "reported_entity_id"],
        unique=False,
    )
    op.create_table(
        "contact_action_events",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("actor_user_id", sa.UUID(), nullable=False),
        sa.Column("target_profile_id", sa.UUID(), nullable=False),
        sa.Column("action_type", sa.Text(), nullable=False),
        sa.Column("source_type", sa.Text(), nullable=True),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("device_id", sa.Text(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action_type in ('call', 'whatsapp', 'show_contact')",
            name=op.f("ck_contact_action_events_action_type_valid"),
        ),
        sa.CheckConstraint(
            "source_type is null or source_type in ('search', 'saved', 'profile', 'work_card', 'work_needed_post')",
            name=op.f("ck_contact_action_events_source_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_contact_action_events_actor_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["target_profile_id"],
            ["profiles.id"],
            name=op.f("fk_contact_action_events_target_profile_id_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_action_events")),
    )
    op.create_index(
        "idx_contact_action_events_actor_created",
        "contact_action_events",
        ["actor_user_id", sa.literal_column("created_at desc")],
        unique=False,
    )
    op.create_index(
        "idx_contact_action_events_target_created",
        "contact_action_events",
        ["target_profile_id", sa.literal_column("created_at desc")],
        unique=False,
    )
    op.create_table(
        "contact_reveals",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("viewer_user_id", sa.UUID(), nullable=False),
        sa.Column("revealed_profile_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.Text(), nullable=True),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("reveal_mode", sa.Text(), nullable=False),
        sa.Column(
            "first_revealed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_revealed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "reveal_count", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("device_id", sa.Text(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reveal_mode in ('free_unlimited', 'quota', 'subscription', 'admin_grant')",
            name=op.f("ck_contact_reveals_reveal_mode_valid"),
        ),
        sa.CheckConstraint(
            "source_type is null or source_type in ('work_card', 'work_needed_post', 'profile', 'saved', 'search')",
            name=op.f("ck_contact_reveals_source_type_valid"),
        ),
        sa.CheckConstraint(
            "last_revealed_at >= first_revealed_at",
            name=op.f("ck_contact_reveals_last_revealed_at_after_first"),
        ),
        sa.CheckConstraint(
            "reveal_count >= 1", name=op.f("ck_contact_reveals_reveal_count_positive")
        ),
        sa.ForeignKeyConstraint(
            ["revealed_profile_id"],
            ["profiles.id"],
            name=op.f("fk_contact_reveals_revealed_profile_id_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["viewer_user_id"],
            ["users.id"],
            name=op.f("fk_contact_reveals_viewer_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_reveals")),
    )
    op.create_index(
        "idx_contact_reveals_profile_created",
        "contact_reveals",
        ["revealed_profile_id", sa.literal_column("created_at desc")],
        unique=False,
    )
    op.create_index(
        "idx_contact_reveals_viewer_created",
        "contact_reveals",
        ["viewer_user_id", sa.literal_column("created_at desc")],
        unique=False,
    )
    op.create_index(
        "uq_contact_reveals_once",
        "contact_reveals",
        ["viewer_user_id", "revealed_profile_id"],
        unique=True,
    )
    op.create_table(
        "profile_view_events",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("viewer_user_id", sa.UUID(), nullable=False),
        sa.Column("viewed_profile_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.Text(), nullable=True),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("device_id", sa.Text(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_type is null or source_type in ('search', 'saved', 'share_link', 'work_card', 'work_needed_post')",
            name=op.f("ck_profile_view_events_source_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["viewed_profile_id"],
            ["profiles.id"],
            name=op.f("fk_profile_view_events_viewed_profile_id_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["viewer_user_id"],
            ["users.id"],
            name=op.f("fk_profile_view_events_viewer_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_view_events")),
    )
    op.create_index(
        "idx_profile_view_events_profile_created",
        "profile_view_events",
        ["viewed_profile_id", sa.literal_column("created_at desc")],
        unique=False,
    )
    op.create_index(
        "idx_profile_view_events_viewer_created",
        "profile_view_events",
        ["viewer_user_id", sa.literal_column("created_at desc")],
        unique=False,
    )
    op.create_table(
        "verification_cases",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("submitted_by_user_id", sa.UUID(), nullable=True),
        sa.Column("case_reason", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.Text(), server_default=sa.text("'draft'"), nullable=False
        ),
        sa.Column("notes_to_user", sa.Text(), nullable=True),
        sa.Column("internal_notes", sa.Text(), nullable=True),
        sa.Column(
            "resubmission_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("consent_version", sa.Text(), nullable=True),
        sa.Column("consent_accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by_admin_user_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "case_reason in ('initial_verification', 'reverification', 'admin_review')",
            name=op.f("ck_verification_cases_case_reason_valid"),
        ),
        sa.CheckConstraint(
            "status in ('draft', 'cancelled') or submitted_at is not null",
            name=op.f("ck_verification_cases_submitted_status_requires_submitted_at"),
        ),
        sa.CheckConstraint(
            "status in ('draft', 'pending_review', 'changes_requested', 'approved', 'rejected', 'cancelled')",
            name=op.f("ck_verification_cases_status_valid"),
        ),
        sa.CheckConstraint(
            "status not in ('changes_requested', 'approved', 'rejected') or reviewed_at is not null",
            name=op.f("ck_verification_cases_reviewed_status_requires_reviewed_at"),
        ),
        sa.CheckConstraint(
            "consent_version is null or consent_accepted_at is not null",
            name=op.f("ck_verification_cases_consent_version_requires_accepted_at"),
        ),
        sa.CheckConstraint(
            "resubmission_count >= 0",
            name=op.f("ck_verification_cases_resubmission_count_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_verification_cases_profile_id_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_admin_user_id"],
            ["admin_users.id"],
            name=op.f("fk_verification_cases_reviewed_by_admin_user_id_admin_users"),
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_user_id"],
            ["users.id"],
            name=op.f("fk_verification_cases_submitted_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_cases")),
    )
    op.create_index(
        "idx_verification_cases_profile_status",
        "verification_cases",
        ["profile_id", "status"],
        unique=False,
    )
    op.create_index(
        "idx_verification_cases_reviewed_by",
        "verification_cases",
        ["reviewed_by_admin_user_id"],
        unique=False,
    )
    op.create_index(
        "idx_verification_cases_submitted_at",
        "verification_cases",
        ["status", "submitted_at"],
        unique=False,
    )
    op.create_index(
        "uq_verification_cases_active_profile",
        "verification_cases",
        ["profile_id"],
        unique=True,
        postgresql_where=sa.text(
            "status in ('draft', 'pending_review', 'changes_requested')"
        ),
    )
    op.create_table(
        "verification_checks",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("verification_case_id", sa.UUID(), nullable=False),
        sa.Column("check_type", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.Text(), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("evidence_media_asset_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_by_admin_user_id", sa.UUID(), nullable=True),
        sa.Column("notes_to_user", sa.Text(), nullable=True),
        sa.Column("internal_notes", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "check_type in ('profile_details', 'mobile', 'shop_or_workplace_photos', 'identity_proof', 'gst_proof', 'admin_final_review')",
            name=op.f("ck_verification_checks_check_type_valid"),
        ),
        sa.CheckConstraint(
            "status in ('pending', 'approved', 'rejected', 'changes_requested', 'not_required')",
            name=op.f("ck_verification_checks_status_valid"),
        ),
        sa.CheckConstraint(
            "status not in ('approved', 'rejected', 'changes_requested') or reviewed_at is not null",
            name=op.f("ck_verification_checks_reviewed_status_requires_reviewed_at"),
        ),
        sa.ForeignKeyConstraint(
            ["evidence_media_asset_id"],
            ["media_assets.id"],
            name=op.f("fk_verification_checks_evidence_media_asset_id_media_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_admin_user_id"],
            ["admin_users.id"],
            name=op.f("fk_verification_checks_reviewed_by_admin_user_id_admin_users"),
        ),
        sa.ForeignKeyConstraint(
            ["verification_case_id"],
            ["verification_cases.id"],
            name=op.f("fk_verification_checks_verification_case_id_verification_cases"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_checks")),
        sa.UniqueConstraint(
            "verification_case_id",
            "check_type",
            name=op.f("uq_verification_checks_verification_case_id"),
        ),
    )
    op.create_index(
        "idx_verification_checks_case_status",
        "verification_checks",
        ["verification_case_id", "status"],
        unique=False,
    )
    op.create_index(
        "idx_verification_checks_evidence",
        "verification_checks",
        ["evidence_media_asset_id"],
        unique=False,
    )
    op.create_index(
        "idx_verification_checks_reviewed_by",
        "verification_checks",
        ["reviewed_by_admin_user_id"],
        unique=False,
    )
    op.create_table(
        "verification_provider_checks",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("verification_case_id", sa.UUID(), nullable=True),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("provider_name", sa.Text(), nullable=False),
        sa.Column("check_type", sa.Text(), nullable=False),
        sa.Column("provider_reference", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "request_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "response_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "check_type in ('gst', 'identity', 'liveness', 'other')",
            name=op.f("ck_verification_provider_checks_check_type_valid"),
        ),
        sa.CheckConstraint(
            "status in ('pending', 'passed', 'failed', 'error')",
            name=op.f("ck_verification_provider_checks_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_verification_provider_checks_profile_id_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["verification_case_id"],
            ["verification_cases.id"],
            name=op.f(
                "fk_verification_provider_checks_verification_case_id_verification_cases"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_provider_checks")),
    )
    op.create_index(
        "idx_verification_provider_checks_case",
        "verification_provider_checks",
        ["verification_case_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_verification_provider_checks_profile",
        "verification_provider_checks",
        ["profile_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_verification_provider_checks_reference",
        "verification_provider_checks",
        ["provider_name", "provider_reference"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_profile_gst_details_proof_media_asset_id_media_assets"),
        "profile_gst_details",
        "media_assets",
        ["proof_media_asset_id"],
        ["id"],
    )

    for table_name in TABLES_WITH_UPDATED_AT:
        op.execute(
            f"""
            create trigger trg_{table_name}_set_updated_at
            before update on public.{table_name}
            for each row
            execute function public.set_updated_at();
            """
        )

    for table_name in TABLES_WITH_RLS:
        op.execute(f"alter table public.{table_name} enable row level security")

    op.execute(
        f"""
        do $$
        begin
          if exists (select 1 from pg_roles where rolname = 'anon') then
            revoke all on {", ".join("public." + table for table in TABLES_WITH_RLS)} from anon;
          end if;
          if exists (select 1 from pg_roles where rolname = 'authenticated') then
            revoke all on {", ".join("public." + table for table in TABLES_WITH_RLS)} from authenticated;
          end if;
        end $$;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in reversed(TABLES_WITH_UPDATED_AT):
        op.execute(
            f"drop trigger if exists trg_{table_name}_set_updated_at on public.{table_name}"
        )

    op.drop_constraint(
        op.f("fk_profile_gst_details_proof_media_asset_id_media_assets"),
        "profile_gst_details",
        type_="foreignkey",
    )
    op.drop_index(
        "idx_verification_provider_checks_reference",
        table_name="verification_provider_checks",
    )
    op.drop_index(
        "idx_verification_provider_checks_profile",
        table_name="verification_provider_checks",
    )
    op.drop_index(
        "idx_verification_provider_checks_case",
        table_name="verification_provider_checks",
    )
    op.drop_table("verification_provider_checks")
    op.drop_index(
        "idx_verification_checks_reviewed_by", table_name="verification_checks"
    )
    op.drop_index("idx_verification_checks_evidence", table_name="verification_checks")
    op.drop_index(
        "idx_verification_checks_case_status", table_name="verification_checks"
    )
    op.drop_table("verification_checks")
    op.drop_index(
        "uq_verification_cases_active_profile",
        table_name="verification_cases",
        postgresql_where=sa.text(
            "status in ('draft', 'pending_review', 'changes_requested')"
        ),
    )
    op.drop_index(
        "idx_verification_cases_submitted_at", table_name="verification_cases"
    )
    op.drop_index("idx_verification_cases_reviewed_by", table_name="verification_cases")
    op.drop_index(
        "idx_verification_cases_profile_status", table_name="verification_cases"
    )
    op.drop_table("verification_cases")
    op.drop_index(
        "idx_profile_view_events_viewer_created", table_name="profile_view_events"
    )
    op.drop_index(
        "idx_profile_view_events_profile_created", table_name="profile_view_events"
    )
    op.drop_table("profile_view_events")
    op.drop_index("uq_contact_reveals_once", table_name="contact_reveals")
    op.drop_index("idx_contact_reveals_viewer_created", table_name="contact_reveals")
    op.drop_index("idx_contact_reveals_profile_created", table_name="contact_reveals")
    op.drop_table("contact_reveals")
    op.drop_index(
        "idx_contact_action_events_target_created", table_name="contact_action_events"
    )
    op.drop_index(
        "idx_contact_action_events_actor_created", table_name="contact_action_events"
    )
    op.drop_table("contact_action_events")
    op.drop_index("idx_reports_target", table_name="reports")
    op.drop_index("idx_reports_status", table_name="reports")
    op.drop_index("idx_reports_reviewed_by", table_name="reports")
    op.drop_index("idx_reports_reporter", table_name="reports")
    op.drop_table("reports")
    op.drop_index(
        "idx_payment_transactions_user_created", table_name="payment_transactions"
    )
    op.drop_index(
        "idx_payment_transactions_subscription", table_name="payment_transactions"
    )
    op.drop_index(
        "idx_payment_transactions_provider_payment", table_name="payment_transactions"
    )
    op.drop_table("payment_transactions")
    op.drop_index(
        "idx_admin_access_grants_user_status", table_name="admin_access_grants"
    )
    op.drop_index("idx_admin_access_grants_admin", table_name="admin_access_grants")
    op.drop_table("admin_access_grants")
    op.drop_index("idx_user_subscriptions_user_status", table_name="user_subscriptions")
    op.drop_index("idx_user_subscriptions_provider", table_name="user_subscriptions")
    op.drop_index("idx_user_subscriptions_plan_status", table_name="user_subscriptions")
    op.drop_table("user_subscriptions")
    op.drop_table("user_contact_quotas")
    op.drop_index("idx_share_events_user_created", table_name="share_events")
    op.drop_index("idx_share_events_target", table_name="share_events")
    op.drop_table("share_events")
    op.drop_index("idx_search_logs_user_created", table_name="search_logs")
    op.drop_index("idx_search_logs_target_created", table_name="search_logs")
    op.drop_index("idx_search_logs_created_at", table_name="search_logs")
    op.drop_table("search_logs")
    op.drop_index("idx_saved_items_user", table_name="saved_items")
    op.drop_index("idx_saved_items_target", table_name="saved_items")
    op.drop_table("saved_items")
    op.drop_index("idx_notifications_user_created", table_name="notifications")
    op.drop_index(
        "idx_notifications_unread",
        table_name="notifications",
        postgresql_where=sa.text("read_at is null"),
    )
    op.drop_table("notifications")
    op.drop_index("idx_media_assets_uploaded_by", table_name="media_assets")
    op.drop_index("idx_media_assets_status", table_name="media_assets")
    op.drop_index(
        "idx_media_assets_private_documents",
        table_name="media_assets",
        postgresql_where=sa.text("visibility = 'private_admin_only'"),
    )
    op.drop_index("idx_media_assets_entity", table_name="media_assets")
    op.drop_table("media_assets")
    op.drop_index("idx_subscription_plans_active", table_name="subscription_plans")
    op.drop_table("subscription_plans")
    # ### end Alembic commands ###
